#ifndef __TBZ_DMA_REG_H_
#define __TBZ_DMA_REG_H_


#define     BMM_M2M_CFG             (*(unsigned char volatile __xdata *)0xfa00)
#define     BMM_M2M_CR              (*(unsigned char volatile __xdata *)0xfa01)
#define     BMM_M2M_STA             (*(unsigned char volatile __xdata *)0xfa02)
#define     BMM_M2M_AMT             (*(unsigned char volatile __xdata *)0xfa03)
#define     BMM_M2M_DONE            (*(unsigned char volatile __xdata *)0xfa04)
#define     BMM_M2M_TXA             (*(unsigned  int volatile __xdata *)0xfa05)
#define     BMM_M2M_TXAH            (*(unsigned char volatile __xdata *)0xfa05)
#define     BMM_M2M_TXAL            (*(unsigned char volatile __xdata *)0xfa06)
#define     BMM_M2M_RXA             (*(unsigned  int volatile __xdata *)0xfa07)
#define     BMM_M2M_RXAH            (*(unsigned char volatile __xdata *)0xfa07)
#define     BMM_M2M_RXAL            (*(unsigned char volatile __xdata *)0xfa08)

#define     BMM_ADC_CFG             (*(unsigned char volatile __xdata *)0xfa10)
#define     BMM_ADC_CR              (*(unsigned char volatile __xdata *)0xfa11)
#define     BMM_ADC_STA             (*(unsigned char volatile __xdata *)0xfa12)
#define     BMM_ADC_RXA             (*(unsigned  int volatile __xdata *)0xfa17)
#define     BMM_ADC_RXAH            (*(unsigned char volatile __xdata *)0xfa17)
#define     BMM_ADC_RXAL            (*(unsigned char volatile __xdata *)0xfa18)
#define     BMM_ADC_CFG2            (*(unsigned char volatile __xdata *)0xfa19)
#define     BMM_ADC_CHSW0           (*(unsigned char volatile __xdata *)0xfa1a)
#define     BMM_ADC_CHSW1           (*(unsigned char volatile __xdata *)0xfa1b)

#define     BMM_SPI_CFG             (*(unsigned char volatile __xdata *)0xfa20)
#define     BMM_SPI_CR              (*(unsigned char volatile __xdata *)0xfa21)
#define     BMM_SPI_STA             (*(unsigned char volatile __xdata *)0xfa22)
#define     BMM_SPI_AMT             (*(unsigned char volatile __xdata *)0xfa23)
#define     BMM_SPI_DONE            (*(unsigned char volatile __xdata *)0xfa24)
#define     BMM_SPI_TXA             (*(unsigned  int volatile __xdata *)0xfa25)
#define     BMM_SPI_TXAH            (*(unsigned char volatile __xdata *)0xfa25)
#define     BMM_SPI_TXAL            (*(unsigned char volatile __xdata *)0xfa26)
#define     BMM_SPI_RXA             (*(unsigned  int volatile __xdata *)0xfa27)
#define     BMM_SPI_RXAH            (*(unsigned char volatile __xdata *)0xfa27)
#define     BMM_SPI_RXAL            (*(unsigned char volatile __xdata *)0xfa28)
#define     BMM_SPI_CFG2            (*(unsigned char volatile __xdata *)0xfa29)

#define     BMM_UR1T_CFG            (*(unsigned char volatile __xdata *)0xfa30)
#define     BMM_UR1T_CR             (*(unsigned char volatile __xdata *)0xfa31)
#define     BMM_UR1T_STA            (*(unsigned char volatile __xdata *)0xfa32)
#define     BMM_UR1T_AMT            (*(unsigned char volatile __xdata *)0xfa33)
#define     BMM_UR1T_DONE           (*(unsigned char volatile __xdata *)0xfa34)
#define     BMM_UR1T_TXA            (*(unsigned  int volatile __xdata *)0xfa35)
#define     BMM_UR1T_TXAH           (*(unsigned char volatile __xdata *)0xfa35)
#define     BMM_UR1T_TXAL           (*(unsigned char volatile __xdata *)0xfa36)
#define     BMM_UR1R_CFG            (*(unsigned char volatile __xdata *)0xfa38)
#define     BMM_UR1R_CR             (*(unsigned char volatile __xdata *)0xfa39)
#define     BMM_UR1R_STA            (*(unsigned char volatile __xdata *)0xfa3a)
#define     BMM_UR1R_AMT            (*(unsigned char volatile __xdata *)0xfa3b)
#define     BMM_UR1R_DONE           (*(unsigned char volatile __xdata *)0xfa3c)
#define     BMM_UR1R_RXA            (*(unsigned  int volatile __xdata *)0xfa3d)
#define     BMM_UR1R_RXAH           (*(unsigned char volatile __xdata *)0xfa3d)
#define     BMM_UR1R_RXAL           (*(unsigned char volatile __xdata *)0xfa3e)

#define     BMM_UR2T_CFG            (*(unsigned char volatile __xdata *)0xfa40)
#define     BMM_UR2T_CR             (*(unsigned char volatile __xdata *)0xfa41)
#define     BMM_UR2T_STA            (*(unsigned char volatile __xdata *)0xfa42)
#define     BMM_UR2T_AMT            (*(unsigned char volatile __xdata *)0xfa43)
#define     BMM_UR2T_DONE           (*(unsigned char volatile __xdata *)0xfa44)
#define     BMM_UR2T_TXA            (*(unsigned  int volatile __xdata *)0xfa45)
#define     BMM_UR2T_TXAH           (*(unsigned char volatile __xdata *)0xfa45)
#define     BMM_UR2T_TXAL           (*(unsigned char volatile __xdata *)0xfa46)
#define     BMM_UR2R_CFG            (*(unsigned char volatile __xdata *)0xfa48)
#define     BMM_UR2R_CR             (*(unsigned char volatile __xdata *)0xfa49)
#define     BMM_UR2R_STA            (*(unsigned char volatile __xdata *)0xfa4a)
#define     BMM_UR2R_AMT            (*(unsigned char volatile __xdata *)0xfa4b)
#define     BMM_UR2R_DONE           (*(unsigned char volatile __xdata *)0xfa4c)
#define     BMM_UR2R_RXA            (*(unsigned  int volatile __xdata *)0xfa4d)
#define     BMM_UR2R_RXAH           (*(unsigned char volatile __xdata *)0xfa4d)
#define     BMM_UR2R_RXAL           (*(unsigned char volatile __xdata *)0xfa4e)

#define     BMM_UR3T_CFG            (*(unsigned char volatile __xdata *)0xfa50)
#define     BMM_UR3T_CR             (*(unsigned char volatile __xdata *)0xfa51)
#define     BMM_UR3T_STA            (*(unsigned char volatile __xdata *)0xfa52)
#define     BMM_UR3T_AMT            (*(unsigned char volatile __xdata *)0xfa53)
#define     BMM_UR3T_DONE           (*(unsigned char volatile __xdata *)0xfa54)
#define     BMM_UR3T_TXA            (*(unsigned  int volatile __xdata *)0xfa55)
#define     BMM_UR3T_TXAH           (*(unsigned char volatile __xdata *)0xfa55)
#define     BMM_UR3T_TXAL           (*(unsigned char volatile __xdata *)0xfa56)
#define     BMM_UR3R_CFG            (*(unsigned char volatile __xdata *)0xfa58)
#define     BMM_UR3R_CR             (*(unsigned char volatile __xdata *)0xfa59)
#define     BMM_UR3R_STA            (*(unsigned char volatile __xdata *)0xfa5a)
#define     BMM_UR3R_AMT            (*(unsigned char volatile __xdata *)0xfa5b)
#define     BMM_UR3R_DONE           (*(unsigned char volatile __xdata *)0xfa5c)
#define     BMM_UR3R_RXA            (*(unsigned  int volatile __xdata *)0xfa5d)
#define     BMM_UR3R_RXAH           (*(unsigned char volatile __xdata *)0xfa5d)
#define     BMM_UR3R_RXAL           (*(unsigned char volatile __xdata *)0xfa5e)

#define     BMM_UR4T_CFG            (*(unsigned char volatile __xdata *)0xfa60)
#define     BMM_UR4T_CR             (*(unsigned char volatile __xdata *)0xfa61)
#define     BMM_UR4T_STA            (*(unsigned char volatile __xdata *)0xfa62)
#define     BMM_UR4T_AMT            (*(unsigned char volatile __xdata *)0xfa63)
#define     BMM_UR4T_DONE           (*(unsigned char volatile __xdata *)0xfa64)
#define     BMM_UR4T_TXA            (*(unsigned  int volatile __xdata *)0xfa65)
#define     BMM_UR4T_TXAH           (*(unsigned char volatile __xdata *)0xfa65)
#define     BMM_UR4T_TXAL           (*(unsigned char volatile __xdata *)0xfa66)
#define     BMM_UR4R_CFG            (*(unsigned char volatile __xdata *)0xfa68)
#define     BMM_UR4R_CR             (*(unsigned char volatile __xdata *)0xfa69)
#define     BMM_UR4R_STA            (*(unsigned char volatile __xdata *)0xfa6a)
#define     BMM_UR4R_AMT            (*(unsigned char volatile __xdata *)0xfa6b)
#define     BMM_UR4R_DONE           (*(unsigned char volatile __xdata *)0xfa6c)
#define     BMM_UR4R_RXA            (*(unsigned  int volatile __xdata *)0xfa6d)
#define     BMM_UR4R_RXAH           (*(unsigned char volatile __xdata *)0xfa6d)
#define     BMM_UR4R_RXAL           (*(unsigned char volatile __xdata *)0xfa6e)

#define     BMM_LCM_CFG             (*(unsigned char volatile __xdata *)0xfa70)
#define     BMM_LCM_CR              (*(unsigned char volatile __xdata *)0xfa71)
#define     BMM_LCM_STA             (*(unsigned char volatile __xdata *)0xfa72)
#define     BMM_LCM_AMT             (*(unsigned char volatile __xdata *)0xfa73)
#define     BMM_LCM_DONE            (*(unsigned char volatile __xdata *)0xfa74)
#define     BMM_LCM_TXA             (*(unsigned  int volatile __xdata *)0xfa75)
#define     BMM_LCM_TXAH            (*(unsigned char volatile __xdata *)0xfa75)
#define     BMM_LCM_TXAL            (*(unsigned char volatile __xdata *)0xfa76)
#define     BMM_LCM_RXA             (*(unsigned  int volatile __xdata *)0xfa77)
#define     BMM_LCM_RXAH            (*(unsigned char volatile __xdata *)0xfa77)
#define     BMM_LCM_RXAL            (*(unsigned char volatile __xdata *)0xfa78)

#endif
